name: 拼接 Forward Widgets 合集

on:
  schedule:
    - cron: '0 3 * * *'  # 每天凌晨3点
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: 聚合拼接 .fwd 文件
      run: |
        echo '{"title": "Forward Widgets 拼接合集", "description": "自动拼接合并", "widgets": [' > merged.fwd
        first=true
        while read -r url; do
          echo "处理链接: $url"
          raw=$(curl -s "$url")

          # 提取 "widgets": [...] 内容
          widgets=$(echo "$raw" | sed -n '/"widgets"[[:space:]]*:/,/\]/p' | sed '1s/^[^[]*\[//' | sed '$s/\][^]]*$//')

          if [ -z "$widgets" ]; then
            echo "⚠️ 跳过空或格式异常链接：$url"
            continue
          fi

          if [ "$first" = true ]; then
            first=false
          else
            echo "," >> merged.fwd
          fi

          echo "$widgets" | sed 's/^/  /' >> merged.fwd
        done < sources.txt
        echo "]}" >> merged.fwd

    - name: 提交更新
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add merged.fwd
        git commit -m "自动拼接 Forward Widgets 合集" || echo "无更新"
        git push
