name: 拼接 Forward Widgets 合集

on:
  schedule:
    - cron: '0 3 * * *'  # 每天凌晨3点
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3 # 或者 @v4, @v5，推荐使用最新版本
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Run aggregation script
      run: python aggregate.py # 如果放在子目录，例如 scripts/，则改为 python scripts/aggregate.py

    - name: Commit and push if changes
      run: |
        git config user.name "github-actions[bot]" # 使用官方 bot 邮箱
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add merged.fwd
        git commit -m "chore: Auto-update Forward Widgets collection" || echo "No changes to commit"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
