name: 自动聚合 Forward Widgets

on:
  schedule:
    - cron: '0 3 * * *'  # 每天凌晨3点自动运行
  workflow_dispatch:      # 支持手动点击触发

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: 安装 jq
      run: sudo apt-get install -y jq

    - name: 聚合 .fwd 内容
      run: |
        echo '{"title": "Forward Widgets 合集", "description": "每日自动更新", "widgets": [' > merged.fwd
        first=true
        while read -r url; do
          echo "正在处理 $url"
          raw=$(curl -s "$url")

          # 判断格式是否正常
          if ! echo "$raw" | jq -e .widgets > /dev/null 2>&1; then
            echo "⚠️ 跳过无法解析的链接：$url"
            continue
          fi

          content=$(echo "$raw" | jq '.widgets[]')

          if [ "$first" = true ]; then
            first=false
          else
            echo "," >> merged.fwd
          fi

          echo "$content" | jq -c '.' >> merged.fwd
        done < sources.txt
        echo ']}' >> merged.fwd

    - name: 提交更新
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add merged.fwd
        git commit -m "每日自动更新 Forward Widgets 合集" || echo "无需更新"
        git push
